### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by jerenuora** [akskokki/forum-app#1]
Huomioita tuotannossa testatessa:

Käyttäjän luomisessa yrittäessä luoda jo olemassa olevan käyttäjän nimisen käyttäjän voisi olla selkeämpi virheilmoitus.

Threadissa jää kaipaamaan suoraa linkkiä takaisin etusivulle.

Login failed sivu kadottaa topicit, mutta näyttää kuitenkin otsikon "Topics:"

Koodista:

Templateja voisi muotoilla sisennyksillä hieman enemmän luettavuuden parantamiseksi. 

Rivin pituuteen voisi kiinnittää tarkempaa huomiota python-koodissa. PEP 8 neuvoo maksimiksi 79 merkkiä, esim. users.py rivit 8 ja 9, routes.py ym. 

Tyyliohjeen mukaan importtien kuuluisi olla omilla riveillään, ei "import a, b ,c"-tapaan

**Comment by akskokki** [comment]
Tosi hyvää palautetta, kiitos ehdotuksista!
