### ISSUE TITLE
Vertaisarviointi #2

### ISSUE THREAD

**Issue by JVS23** [akskokki/forum-app#3]
Vertaisarviointi tehty 21/02/2023 kello 20:00.

## Sovellustestaus: 

Ohjelma toimi fly.io:ssa hyvin, ja pääsin kirjautumaan sisään adminilla sekä tekemään oman käyttäjäni.
Kokeilin kaikkia READMEn mainitsemia ominaisuuksia ja kaikki vaikutti toimivan hyvin, erinomaista! 
Lokaali asennus toimii myös kuten pitääkin.

Huomioita: 

- Oman threadin editoimisen käyttöliittymä oli hyvin vaikuttava!
- Pidin myös siitä että sisällytit salasanan vahvistamisen, itselläni ei tuota tullut mieleen vaikka
toiminnallisuus onkin erittäin tärkeä.
- Ulkoasu on melko simppeli, mutta myös siisti, responsiivinen ja helposti navigoitava.
- Admineilla voisi mahdollisesti olla oikeus poistaa muiden tekemiä threadeja/viestejä jos haluat,
ymmärrettävää tosin että julkisella adminilla näitä oikeuksia ei nyt ole :D

## Koodikatselmointi:

- Salasanoilla ja käyttäjänimillä on tarkistus vain yli 0:n pituisille merkkijonoille, mutta voisi olla hyvä idea
asettaa niille ylärajakin.
- Tietokannat näyttävät hyviltä, minimimäärään tarvitaan vielä yksi lisää mutta README:n mukaan se 
vaikuttaisikin olevan jo työn alla.  Myös SQL-kutsut olivat siistejä ja injektioilta on suojauduttu, hyvä!
- Koodi on hyvin modularisoitu omiin komponentteihinsa, toki jos rootista haluaa hieman siistimmän,
voi vielä tehdä app-kansion tai vastaavan johon sovelluksen koodi menee,
jolloin rootin sekä Githubin näkymästä tulee hieman selkeämpi.
- En ainakaan huomannut CSRF-haavoittuvuuksilta suojautumista vielä, se voisi olla hyvä lisä.
- Vinkki: voit halutessasi muokata bootstrapin "päälle" omia tyylejäsi tekemällä oman css-tiedoston, ja importtaamalla
sen html-tiedostoon bootstrapin jälkeen. Näin pääset muuttamaan pieniä yksityiskohtia melko vaivattomasti.

Sovellus näyttää olevan erittäin hyvässä vaiheessa, ja aikaakin on vielä reippaasti toteuttaa haluamasi
ominaisuudet.
Hyvää työtä ja tsemppiä viimeistelyihin!

**Comment by akskokki** [comment]
Kiitokset tosi hyvästä palautteesta! CSRF-haavoittuvuudet ja syötteiden maksimipituudet ovat nyt kurissa. 

Erityisesti arvostan kehuja threadinmuokkaus-UI:sta, olin itsekin kovin tyytyväinen siitä miten sain sen toimimaan. :D
